/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package point.of.sale.system;

import java.io.File;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Anakin, Will, Eric
 */
public class SalePage extends javax.swing.JFrame {

    /**
     * Creates new form SalePage
     */
    public SalePage(String name) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.cashierName = name;
    }

    private String cashierName;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        appleText = new javax.swing.JTextField();
        bananaText = new javax.swing.JTextField();
        cherryText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jb2 = new javax.swing.JButton();
        appleCheck = new javax.swing.JCheckBox();
        bananaCheck = new javax.swing.JCheckBox();
        cherryCheck = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sales Menu");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setText("Item");

        appleText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleTextActionPerformed(evt);
            }
        });

        bananaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bananaTextActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total");

        totalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTextActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setText("Number to buy");

        jb1.setText("Calculate");
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jb2.setText("Buy");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        appleCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        appleCheck.setText("Apple $3.00/bag");
        appleCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appleCheckActionPerformed(evt);
            }
        });

        bananaCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bananaCheck.setText("Banana $2.00/bag");

        cherryCheck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cherryCheck.setText("Cherry $5.00/bag");

        jButton2.setText("Check Inventory");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("History");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(appleCheck)
                                .addComponent(bananaCheck)
                                .addComponent(cherryCheck))
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cherryText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bananaText, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(appleText)))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jButton3)
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(72, 72, 72)
                                            .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jb1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                            .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(201, 201, 201))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(appleCheck)
                    .addComponent(appleText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bananaCheck)
                    .addComponent(bananaText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cherryText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cherryCheck))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(totalText, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb1)
                    .addComponent(jb2)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void appleTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleTextActionPerformed

    }//GEN-LAST:event_appleTextActionPerformed

    private void totalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTextActionPerformed

    }//GEN-LAST:event_totalTextActionPerformed

    private void appleCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appleCheckActionPerformed

    }//GEN-LAST:event_appleCheckActionPerformed

    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        totalText.setText(this.totalCalc() + "");
    }//GEN-LAST:event_jb1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        int appleNum = 0, bananaNum = 0, cherryNum = 0;
        long appleNum_inv = 0, bananaNum_inv = 0, cherryNum_inv = 0;

        if (appleCheck.isSelected()) {
            if ((appleText.getText().matches("\\D+")) || appleText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            appleNum = Integer.parseInt(appleText.getText());
        }
        if (bananaCheck.isSelected()) {
            if ((bananaText.getText().matches("\\D+")) || bananaText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            bananaNum = Integer.parseInt(bananaText.getText());
        }
        if (cherryCheck.isSelected()) {
            if ((cherryText.getText().matches("\\D+")) || cherryText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            cherryNum = Integer.parseInt(cherryText.getText());
        }

        this.writeTransaction(appleNum, bananaNum, cherryNum);
        JSONParser parser = new JSONParser();
        try {

            Object obj = parser.parse(new FileReader("C:\\SEIS602 Java\\inventory\\info.json"));
            JSONObject jobj = (JSONObject) obj;
            appleNum_inv = (long) jobj.get("apple");
            bananaNum_inv = (long) jobj.get("banana");
            cherryNum_inv = (long) jobj.get("cherry");
        } catch (Exception e) {
            e.printStackTrace();
        }

        appleNum_inv = appleNum_inv - appleNum;
        if (appleNum_inv <= 20) {
            appleNum_inv += 50;
            JOptionPane.showMessageDialog(null, "Apple Low Inventory" + "\nAuto Update to  " + appleNum_inv, "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
        bananaNum_inv = bananaNum_inv - bananaNum;
        if (bananaNum_inv <= 20) {
            bananaNum_inv += 50;
            JOptionPane.showMessageDialog(null, "Banana Low Inventory" + "\nAuto Update to  " + bananaNum_inv, "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }
        cherryNum_inv = cherryNum_inv - cherryNum;
        if (cherryNum_inv <= 20) {
            cherryNum_inv += 50;
            JOptionPane.showMessageDialog(null, "Cherry Low Inventory" + "\nAuto Update to  " + cherryNum_inv, "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
        }

        JsonWR inventoryChange = new JsonWR();
        inventoryChange.inventoryWrite(inventoryChange.json_obj(appleNum_inv, bananaNum_inv, cherryNum_inv));
        JsonWR historyChange = new JsonWR();
        historyChange.historyWrite(historyChange.json_obj_history(cashierName, appleNum, bananaNum, cherryNum, this.totalCalc()));
    }//GEN-LAST:event_jb2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        InventoryList il = new InventoryList();
        il.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void bananaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bananaTextActionPerformed

    }//GEN-LAST:event_bananaTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        final String historyPath = "C:\\SEIS602 Java\\history\\history.json";

        JSONParser parser = new JSONParser();

        try {

            Object obj_history = parser.parse(new FileReader(historyPath));

            JSONObject jobj_history = (JSONObject) obj_history;

            Object name = jobj_history.get("name");
            Object totalSale = jobj_history.get("Total Sale");
            Object appleHist = jobj_history.get("apple");
            Object bananaHist = jobj_history.get("banana");
            Object cherryHist = jobj_history.get("cherry");

            JOptionPane.showMessageDialog(null, name + "\n" + "Sale Amount: " + totalSale + "\n" + "Apple: " + appleHist + "\n" + "Banana: " + bananaHist + "\n" + "Cherry: " + cherryHist,
                    "MESSAGE", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void UpdateInventory() {

    }

    public void writeTransaction(int appleNum, int bananaNum, int cherryNum) {
        File file = new File("C:\\SEIS602 Java\\transaction");
        File[] files = file.listFiles();
        int num = 100;
        for (File f : files) {
            if (Integer.parseInt(f.getName().substring(0, 3)) > num) {
                num = Integer.parseInt(f.getName().substring(0, 3));
            }
        }

        JsonWR jsonwriter = new JsonWR();
        jsonwriter.transactionWrite(jsonwriter.json_obj(appleNum, bananaNum, cherryNum),
                "C:\\SEIS602 Java\\transaction\\", num + 1);

        int transN = num + 1;
        jLabel3.setText("Transaction No. : " + transN);
    }

    public void writeInventory() {

    }

    public double totalCalc() {
        final double applePerBag = 3;
        final double bananaPerBag = 2;
        final double cherryPerBag = 5;
        double appleTotal = 0;
        double bananaTotal = 0;
        double cherryTotal = 0;
        if (appleCheck.isSelected()) {
            if ((appleText.getText().matches("\\D+")) || appleText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            appleTotal = applePerBag * Double.parseDouble(appleText.getText());
        }
        if (bananaCheck.isSelected()) {
            if ((bananaText.getText().matches("\\D+")) || bananaText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            bananaTotal = bananaPerBag * Double.parseDouble(bananaText.getText());
        }
        if (cherryCheck.isSelected()) {
            if ((cherryText.getText().matches("\\D+")) || cherryText.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "input invalid", "WARNING_MESSAGE", JOptionPane.WARNING_MESSAGE);
            }
            cherryTotal = cherryPerBag * Double.parseDouble(cherryText.getText());
        }

        return appleTotal + bananaTotal + cherryTotal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox appleCheck;
    private javax.swing.JTextField appleText;
    private javax.swing.JCheckBox bananaCheck;
    private javax.swing.JTextField bananaText;
    private javax.swing.JCheckBox cherryCheck;
    private javax.swing.JTextField cherryText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JTextField totalText;
    // End of variables declaration//GEN-END:variables
}
